name: Django CI

on:
  push:
    branches: 
      - "develop/transprensa"
      - "feat/transprensa"
  pull_request:
    branches: 
      - "develop/transprensa"
      - "feat/transprensa"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.13.7']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Django System Check
      run: |
        python manage.py check
    - name: Run Tests
      run: |
        python manage.py test

  auto-merge:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop/transprensa' && success()
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Automatic Merge to feat/transprensa
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git checkout feat/transprensa
        git pull origin feat/transprensa
        git merge --no-ff origin/develop/transprensa -m "Merge develop/transprensa into feat/transprensa"
        git push origin feat/transprensa